image: inskale

stages:
  - deploy

deploy-develop:
  stage: deploy

  before_script:
    - git config --global user.email "yannick.wieland@hs-pforzheim.de"
    - git config --global user.name "Automated Develop Deployment"
    - chmod +x ./Pyodide/Scripts/clearFTPServerDev.sh
    - chmod +x ./Pyodide/Scripts/createDevRedirectIndex.sh
    - lcapyPkgName=$(ls Pyodide/Packages | grep 'lcapy*' | head -n 1)
    - schemdrawPkgName=$(ls Pyodide/Packages | grep 'schemdraw*' | head -n 1)
    - simplipfyPkgName=$(ls Pyodide/Packages | grep 'simplipfy*' | head -n 1)
    - pip3 install Pyodide/Packages/$lcapyPkgName
    - pip3 install Pyodide/Packages/$schemdrawPkgName
    - pip3 install Pyodide/Packages/$simplipfyPkgName
    - apk add --no-cache curl
    - curl --location --output /usr/local/bin/release-cli "https://gitlab.com/api/v4/projects/gitlab-org%2Frelease-cli/packages/generic/release-cli/latest/release-cli-linux-amd64"
    - chmod +x /usr/local/bin/release-cli
    - release-cli -v

  script:
    - commitMsg=$(git log -1 --pretty=%B)
    - echo "On branch - $CI_COMMIT_BRANCH commit - $commitMsg"
    - ls -la  # List files from the tag's commit
    - ./Pyodide/Scripts/clearFTPServerDev.sh
    - cp ./Pyodide/Scripts/UpdateInProgress.html ./index.html
    - ncftpput -u $FTP_USER -p $FTP_PASS -S .tmp $FTP_SERVER $FTP_FOLDER_DEV ./index.html
    - ./Pyodide/Scripts/createDevRedirectIndex.sh
    - cd Pyodide/
    - ls -a
    # generate svg files for circuit selector
    - python3 Scripts/generateSVGFiles.py
    - rm -rf __pycache__
    - zip -r Circuits Circuits && rm -r Circuits/
    # remove files that should not be on simplipfy.org
    - rm -rf .idea/
    - rm -rf .gitignore
    - rm -rf GzipSimplePythonHttpServer.py
    - rm -rf Scripts/
    # upload all files to ftp server
    - ncftpput -u $FTP_USER -p $FTP_PASS -m -R $FTP_SERVER $FTP_FOLDER_DEV/$CI_COMMIT_SHA/ ./
    # upload simpliPFy index.html (override maintenance index.html)
    - cd ..
    - ncftpput -u $FTP_USER -p $FTP_PASS -S .tmp $FTP_SERVER $FTP_FOLDER_DEV ./index.html

  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - when: always


deploy-profSky:
  stage: deploy

  before_script:
  - git config --global user.email "yannick.wieland@hs-pforzheim.de"
  - git config --global user.name "Automated Release Deployment"
  - chmod +x ./Pyodide/Scripts/copyFiles.sh
  - lcapyPkgName=$(ls Pyodide/Packages | grep 'lcapy*' | head -n 1)
  - schemdrawPkgName=$(ls Pyodide/Packages | grep 'schemdraw*' | head -n 1)
  - simplipfyPkgName=$(ls Pyodide/Packages | grep 'simplipfy*' | head -n 1)
  - pip3 install Pyodide/Packages/$lcapyPkgName
  - pip3 install Pyodide/Packages/$schemdrawPkgName
  - pip3 install Pyodide/Packages/$simplipfyPkgName

  script:
    - echo $CI_COMMIT_SHA
    - commitMsg=$(git log -1 --pretty=%B)
    - echo $commitMsg
    - git rev-parse HEAD
    # generate svg files for circuit selector
    - cd Pyodide
    - python3 ./Scripts/generateSVGFiles.py
    - rm -rf __pycache__
    - zip -r Circuits Circuits
    - cd ..
    # upload to github of prof-sky asdf
    - sed -i /setSiteId/s/'2'/'3'/ ./Pyodide/src/scripts/utils/matomoHelper.js
    - git submodule update --init --recursive
    - cd lcapy-inskale
    - git checkout $(git rev-list --tags --max-count=1)
    - cd ..
    - git commit . -m "created files for release"
    - git branch
    - git branch -D temp
    - git fetch https://github.com/prof-sky/simplipfy.git main:temp
    - git checkout temp
    - git rm -rf lcapy-inskale/
    - git commit -m "remove submodule"
    - git rev-parse HEAD
    - git merge $CI_COMMIT_SHA --squash --allow-unrelated-histories -X theirs
    - git submodule update --init --recursive
    - cd lcapy-inskale
    - git checkout $(git rev-list --tags --max-count=1)
    - cd ..
    - git commit --amend -m "${commitMsg}"
    - git push https://${PAT_TH}@github.com/prof-sky/simplipfy.git temp:main --force


  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


deploy-release:
  stage: deploy
  rules:
    - if: "$CI_COMMIT_TAG"

  before_script:
    - export FTP_SERVER_FULL_PATH="ftp://${FTP_SERVER}${FTP_FOLDER}"
    - export versionPath=$FTP_SERVER$FTP_FOLDER/$CI_COMMIT_TAG
    - git config --global user.email "yannick.wieland@hs-pforzheim.de"
    - git config --global user.name "Automated Release Deployment"
    - chmod +x ./Pyodide/Scripts/createRedirectIndex.sh
    - lcapyPkgName=$(ls Pyodide/Packages | grep 'lcapy*' | head -n 1)
    - schemdrawPkgName=$(ls Pyodide/Packages | grep 'schemdraw*' | head -n 1)
    - simplipfyPkgName=$(ls Pyodide/Packages | grep 'simplipfy*' | head -n 1)
    - pip3 install Pyodide/Packages/$lcapyPkgName
    - pip3 install Pyodide/Packages/$schemdrawPkgName
    - pip3 install Pyodide/Packages/$simplipfyPkgName
    - apk add uglify-js
    - apk add --no-cache curl
    - curl --location --output /usr/local/bin/release-cli "https://gitlab.com/api/v4/projects/gitlab-org%2Frelease-cli/packages/generic/release-cli/latest/release-cli-linux-amd64"
    - chmod +x /usr/local/bin/release-cli
    - release-cli -v

  script:
    - versionPath=$FTP_SERVER$FTP_FOLDER/$CI_COMMIT_TAG
    - echo "Checking out tag $CI_COMMIT_TAG..."
    - git fetch --tags  # Fetch tags to ensure they are available
    - git checkout $CI_COMMIT_TAG  # Checkout the tag
    - ls -la  # List files from the tag's commit
    - ./Pyodide/Scripts/createRedirectIndex.sh
    - cd Pyodide/
    - ls -a
    # generate svg files for circuit selector
    - python3 Scripts/generateSVGFiles.py
    - rm -rf __pycache__
    - zip -r Circuits Circuits && rm -r Circuits/
    # remove files that should not be on simplipfy.org
    - rm -rf .idea/
    - rm -rf .gitignore
    - rm -rf GzipSimplePythonHttpServer.py
    - rm -rf Scripts/
    - |
      # Rekursiv durch alle .js-Dateien im src/ Verzeichnis iterieren
      find src/ -type f -name "*.js" | while read file; do
      # Zieldatei mit .min.js Endung
      min_file="${file%.js}.min.js"
      # Minifizieren und die Datei mit der .min.js-Endung speichern
      uglifyjs "$file" -o "$file" -c -m
      done
    # upload all files to ftp server
    - sed -i /setSiteId/s/'2'/'1'/ ./src/scripts/utils/matomoHelper.js
    - ncftpput -u $FTP_USER -p $FTP_PASS -m -R $FTP_SERVER $FTP_FOLDER/$CI_COMMIT_TAG/ ./
    # upload simpliPFy index.html (override maintenance index.html)
    - cd ..
    - ncftpput -u $FTP_USER -p $FTP_PASS -S .tmp $FTP_SERVER $FTP_FOLDER ./index.html


  artifacts:
    paths:
      - Pyodide/

  release: # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: "Server Files"
          url: "https://gitlab.hs-pforzheim.de/stefan.kray/inskale/-/jobs/${CI_JOB_ID}/artifacts/download?artifact_path=Pyodide%2F"
