.git_config: &git_config
  - git config --global user.email "yannick.wieland@hs-pforzheim.de"
  - git config --global user.name "gitlab-ci-runner"

.install_packages: &install_packages
  - lcapyPkgName=$(ls Pyodide/Packages | grep 'lcapy*' | head -n 1)
  - schemdrawPkgName=$(ls Pyodide/Packages | grep 'schemdraw*' | head -n 1)
  - simplipfyPkgName=$(ls Pyodide/Packages | grep 'simplipfy*' | head -n 1)
  - genDrawPkgName=$(ls Pyodide/Packages | grep 'generalizenetlistdrawing*' | head -n 1)
  - "echo \"lcapyPkgName: $lcapyPkgName\""
  - "echo \"schemdrawPkgName: $schemdrawPkgName\""
  - "echo \"simplipfyPkgName: $simplipfyPkgName\""
  - "echo \"genDrawPkgName: $genDrawPkgName\""
  - pip install Pyodide/Packages/$lcapyPkgName
  - pip install Pyodide/Packages/$schemdrawPkgName
  - pip install Pyodide/Packages/$genDrawPkgName
  - pip install Pyodide/Packages/$simplipfyPkgName
  - pip install -e Pyodide/Scripts/

.release_cli: &release_cli
  - apk add --no-cache curl
  - curl --location --output /usr/local/bin/release-cli "https://gitlab.com/api/v4/projects/gitlab-org%2Frelease-cli/packages/generic/release-cli/latest/release-cli-linux-amd64"
  - chmod +x /usr/local/bin/release-cli
  - release-cli -v

.make_scripts_executable: &make_scripts_executable
  - echo "skipped, no scripts to make executable"


.echo_branch_and_commitMsg: &echo_branch_and_commitMsg
  - commitMsg=$(git log -1 --pretty=%B)
  - echo "On branch - $CI_COMMIT_BRANCH commit - $commitMsg"

.generate_svg_files: &generate_svg_files
  - cd $CI_PROJECT_DIR
  - cd ./Pyodide
  - python3 ./Scripts/generateSVGFiles.py -path Circuits
  - rm -rf __pycache__
  - zip -r Circuits Circuits && rm -r Circuits/

.navigate_into_pyodide: &navigate_into_pyodide
  - cd $CI_PROJECT_DIR
  - cd ./Pyodide

image: inskale
stages:
  - pre_check
  - deploy

# check if pipelines are blocked. Blocked pipelines get an extra with && $EXEC_PIPELINES in their condition.
# some pipeliens always run so the script should not exit here.
check_pipeline_blocked:
  stage: pre_check
  script:
    - |
      if [ "$EXEC_PIPELINES" != "true" ]; then
        echo "⚠️  Pipeline execution blocked in GitLab. Set EXEC_PIPELINES=true to enable."
        exit 1
      fi
  rules:
    - when: always

deploy-develop:
  stage: deploy

  before_script:
    - *git_config
    - *install_packages

  script:
    - *echo_branch_and_commitMsg
    - python ./Pyodide/Scripts/cli/release.py --target dev

  resource_group: ftp-server

  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH == "main"'
      when: never
    - if: '$EXEC_PIPELINES == "true"'
      when: always
    - when: never

  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_DEPTH: 1

deploy-profSky:
  stage: deploy

  before_script:
  - *git_config
  - *install_packages

  script:
    - *echo_branch_and_commitMsg
    - echo "Commit SHA - $CI_COMMIT_SHA"
    - git rev-parse HEAD
    # generate svg files for circuit selector
    - *generate_svg_files
    # upload to github of prof-sky asdf
    - cd $CI_PROJECT_DIR
    - sed -i /setSiteId/s/'2'/'3'/ ./Pyodide/src/scripts/utils/matomoHelper.js
    - git submodule update --init --recursive
    - cd lcapy-inskale
    - git checkout $(git rev-list --tags --max-count=1)
    - cd ..
    - git commit . -m "created files for release"
    - git branch -D temp || true
    - git fetch https://github.com/prof-sky/simplipfy.git main:temp
    - git checkout temp
    - git rm -rf lcapy-inskale/
    - git commit -m "remove submodule"
    - git rev-parse HEAD
    - git merge $CI_COMMIT_SHA --squash --allow-unrelated-histories -X theirs
    - git submodule update --init --recursive
    - cd lcapy-inskale
    - git checkout $(git rev-list --tags --max-count=1)
    - cd ..
    - git commit --amend -m "${commitMsg}"
    - git push https://${PAT_TH}@github.com/prof-sky/simplipfy.git temp:main --force


  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $EXEC_PIPELINES == "true"'
      when: always
    - when: never

  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_DEPTH: 1


deploy-release:
  stage: deploy
  rules:
    - if: "$CI_COMMIT_TAG"

  before_script:
    - *git_config
    - *install_packages

  script:
    - echo "Checking out tag $CI_COMMIT_TAG..."
    - git fetch --tags  # Fetch tags to ensure they are available
    - git checkout $CI_COMMIT_TAG  # Checkout the tag
    - python ./Pyodide/Scripts/cli/release.py --target simplipfy

  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_DEPTH: 1

  artifacts:
    paths:
      - Pyodide/

  release: # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: "Server Files"
          url: "https://gitlab.hs-pforzheim.de/stefan.kray/inskale/-/jobs/${CI_JOB_ID}/artifacts/download?artifact_path=Pyodide%2F"
