ServerName "Docker FTP Server"

ServerType standalone
AllowOverwrite on

<Global>
    RequireValidShell off
</Global>

# Disable IPv6 (if wanted)
UseIPv6 off

# Set home directory as root directory for FTP users
DefaultRoot ~

Port 21
Umask 022

<Global>
    RequireValidShell off
</Global>

<IfModule mod_tls.c>
    TLSEngine on
    TLSLog /var/log/proftpd/tls.log
    TLSProtocol TLSv1.2
    TLSRSACertificateFile /etc/ssl/certs/proftpd.crt
    TLSRSACertificateKeyFile /etc/ssl/private/proftpd.key
    TLSVerifyClient off
    TLSOptions NoSessionReuseRequired
    TLSRequired on
</IfModule>